language: python
python:
  - "2.7"
  - "3.3"
before_install:
  - pip install sympy==0.7.3 --use-mirrors
  - pip install numpy==1.7.1 --use-mirrors
  - sudo apt-get install python-cvxopt
  - sudo apt-get build-dep python-cvxopt
  - pip install cvxopt --use-mirrors
  - pip install scipy --use-mirrors
  - pip install coveralls --use-mirrors
install:
  - python setup.py install
script:
  - ./run_tests.sh
after_script:
  - coveralls
